### ISSUE TITLE
org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration

### ISSUE THREAD

**Issue by thkfighter** [openTCS/opentcs-integration-example#3]
## Affected version

project.ext.openTcsBaselineVersion = '5.13.0'
project.ext.vda5050CommAdapterVersion = '0.18.0'

## Steps to reproduce

1. Clone a project from opentcs-integration-example.
2. In the generated project, run gradle task openTCS-<name>-Kernel [run].

### Expected behaviour

openTCS Kernel runs without errors.

### Actual behaviour

```
[20240311-18:53:26-335] INFO    main                 o.o.util.Environment.logSystemInfo()                   : openTCS baseline version: 5.13.0 (build date: 2024-02-22 13:53:04), customization 'Rexroth' version 0.1.0-SNAPSHOT (build date: 2024-03-11 17:29:20), Java: 13.0.14, Azul Systems, Inc.; JVM: 13.0.14+5-MTS, Azul Systems, Inc.; OS: Linux, amd64
[20240311-18:53:26-371] INFO    main                 o.o.kernel.RunKernel.configurationBindingProvider()    : Using gestalt as the configuration provider.
[20240311-18:53:26-400] INFO    main                 o.o.c.gestalt.GestaltConfigurationBindingProvider.reloadInterval(): Using configuration reload interval of 10000 ms.
[20240311-18:53:26-402] INFO    main                 o.o.c.gestalt.GestaltConfigurationBindingProvider.buildSources(): Using default configuration file /home/damon/workspace/openTCS-Integration-5.13/openTCS-Integration-Rexroth/openTCS-Rexroth-Kernel/build/install/openTCS-Rexroth-Kernel/./config/opentcs-kernel-defaults-baseline.properties...
[20240311-18:53:26-411] INFO    main                 o.o.c.gestalt.GestaltConfigurationBindingProvider.buildSources(): Using overrides from supplementary configuration file /home/damon/workspace/openTCS-Integration-5.13/openTCS-Integration-Rexroth/openTCS-Rexroth-Kernel/build/install/openTCS-Rexroth-Kernel/./config/opentcs-kernel-defaults-custom.properties...
[20240311-18:53:26-412] INFO    main                 o.o.c.gestalt.GestaltConfigurationBindingProvider.buildSources(): Using overrides from supplementary configuration file /home/damon/workspace/openTCS-Integration-5.13/openTCS-Integration-Rexroth/openTCS-Rexroth-Kernel/build/install/openTCS-Rexroth-Kernel/./config/opentcs-kernel.properties...
[20240311-18:53:26-476] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module com.rexroth.kernel.extensions.statistics.StatisticsModule (source: (file:/home/damon/workspace/openTCS-Integration-5.13/openTCS-Integration-Rexroth/openTCS-Rexroth-KernelExtension-Statistics/build/libs/opentcs-rexroth-kernelextension-statistics-0.1.0-SNAPSHOT.jar <no signer certificates>))
[20240311-18:53:26-478] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.commadapter.vehicle.vda5050.KernelInjectionModuleImpl (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs.commadapter.vehicle.vda5050/opentcs-commadapter-vda5050/0.18.0/d726302cd80b4ef47d2c72a2e96650763f6f311a/opentcs-commadapter-vda5050-0.18.0.jar <no signer certificates>))
[20240311-18:53:26-478] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.virtualvehicle.LoopbackCommAdapterModule (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs/opentcs-commadapter-loopback/5.13.0/d95cb73ef44895a37ebe5b37d9fe7e8417773937/opentcs-commadapter-loopback-5.13.0.jar <no signer certificates>))
[20240311-18:53:26-479] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.commadapter.peripheral.loopback.LoopbackPeripheralKernelModule (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs/opentcs-peripheralcommadapter-loopback/5.13.0/dbc6e74b807da1a83bb7696dcdc184d680a5b7a9/opentcs-peripheralcommadapter-loopback-5.13.0.jar <no signer certificates>))
[20240311-18:53:26-480] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.kernel.extensions.adminwebapi.AdminWebApiModule (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs/opentcs-kernel-extension-http-services/5.13.0/d66588cb3978514b430a8d1e5f1986295e5d1b24/opentcs-kernel-extension-http-services-5.13.0.jar <no signer certificates>))
[20240311-18:53:26-481] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.kernel.extensions.servicewebapi.ServiceWebApiModule (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs/opentcs-kernel-extension-http-services/5.13.0/d66588cb3978514b430a8d1e5f1986295e5d1b24/opentcs-kernel-extension-http-services-5.13.0.jar <no signer certificates>))
[20240311-18:53:26-481] INFO    main                 o.o.kernel.RunKernel.findRegisteredModules()           : Integrating injection module org.opentcs.kernel.extensions.rmi.RmiServicesModule (source: (file:/home/damon/.gradle/caches/modules-2/files-2.1/org.opentcs/opentcs-kernel-extension-rmi-services/5.13.0/1c2c17747361bced3cf1d8e3e0ea26476a0a1455/opentcs-kernel-extension-rmi-services-5.13.0.jar <no signer certificates>))
[20240311-18:53:26-695] WARNING main                 o.o.k.e.rmi.RmiServicesModule.configure()              : SSL encryption disabled, connections will not be secured!
[20240311-18:53:26-712] INFO    main                 c.g.i.internal.MessageProcessor.visit()                : An exception was caught and reported. Message: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, field onOpModeChangeDoUpdateIntegrationLevel results in null value
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, field onOpModeChangeDoWithdrawOrder results in null value
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, field onOpModeChangeDoResetPosition results in null value
org.opentcs.configuration.ConfigurationException: Cannot get configuration value for prefix: 'commadapter.vehicle.vda5050'
	at org.opentcs.configuration.gestalt.GestaltConfigurationBindingProvider.get(GestaltConfigurationBindingProvider.java:84)
	at org.opentcs.commadapter.vehicle.vda5050.KernelInjectionModuleImpl.configure(KernelInjectionModuleImpl.java:29)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:236)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.opentcs.kernel.RunKernel.main(RunKernel.java:61)
Caused by: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, for class: ObjectToken, during navigating to next node
Caused by: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration

 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, field onOpModeChangeDoUpdateIntegrationLevel results in null value
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, field onOpModeChangeDoWithdrawOrder results in null value
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, field onOpModeChangeDoResetPosition results in null value
	at org.github.gestalt.config.GestaltCore.getConfigInternal(GestaltCore.java:364)
	at org.github.gestalt.config.GestaltCore.getConfig(GestaltCore.java:271)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:66)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:56)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:45)
	at org.opentcs.configuration.gestalt.GestaltConfigurationBindingProvider.get(GestaltConfigurationBindingProvider.java:80)
	... 14 more

[20240311-18:53:26-957] SEVERE  main                 o.o.u.logging.UncaughtExceptionLogger.uncaughtException(): Unhandled exception
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: Cannot get configuration value for prefix: 'commadapter.vehicle.vda5050'
  at Modules$OverrideModule.configure(Modules.java:236)

2) [Guice/MissingImplementation]: No implementation for CommAdapterConfiguration was bound.

Requested by:
1  : KernelInjectionModuleImpl.configure(KernelInjectionModuleImpl.java:28)
      \_ installed by: Modules$OverrideModule -> KernelInjectionModuleImpl

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
CommAdapterConfiguration:  "org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration"
KernelInjectionModuleImpl: "org.opentcs.commadapter.vehicle.vda5050.KernelInjectionModuleImpl"
Modules$OverrideModule:    "com.google.inject.util.Modules$OverrideModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:576)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.opentcs.kernel.RunKernel.main(RunKernel.java:61)
Caused by: org.opentcs.configuration.ConfigurationException: Cannot get configuration value for prefix: 'commadapter.vehicle.vda5050'
	at org.opentcs.configuration.gestalt.GestaltConfigurationBindingProvider.get(GestaltConfigurationBindingProvider.java:84)
Caused by: org.opentcs.configuration.ConfigurationException: Cannot get configuration value for prefix: 'commadapter.vehicle.vda5050'

	at org.opentcs.commadapter.vehicle.vda5050.KernelInjectionModuleImpl.configure(KernelInjectionModuleImpl.java:29)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:236)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
	at com.google.inject.spi.Elements.getElements(Elements.java:108)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	... 4 more
Caused by: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoUpdateIntegrationLevel, field onOpModeChangeDoUpdateIntegrationLevel results in null value
Caused by: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: commadapter.vehicle.vda5050, for class: org.opentcs.commadapter.vehicle.vda5050.CommAdapterConfiguration

 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoWithdrawOrder, field onOpModeChangeDoWithdrawOrder results in null value
 - level: MISSING_VALUE, message: Unable to find node matching path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, for class: ObjectToken, during navigating to next node
 - level: ERROR, message: Decoding object : CommAdapterConfiguration on path: commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition, field onOpModeChangeDoResetPosition results in null value
	at org.github.gestalt.config.GestaltCore.getConfigInternal(GestaltCore.java:364)
	at org.github.gestalt.config.GestaltCore.getConfig(GestaltCore.java:271)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:66)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:56)
	at org.github.gestalt.config.GestaltCache.getConfig(GestaltCache.java:45)
	at org.opentcs.configuration.gestalt.GestaltConfigurationBindingProvider.get(GestaltConfigurationBindingProvider.java:80)
	... 14 more
```

### Additional information

* Operating system and version: Ubuntu Linux 22.04
* Java distribution version: AdoptOpenJDK 13.0.2+8
* Gradle 8.6

**Comment by martingr** [comment]
This issue is related to a switch to the Gestalt library as an alternative (to the cfg4j library) for configuring the openTCS applications. A fix for this will be included in openTCS 5.14. 

Until openTCS 5.14 is published, you can set the system property `opentcs.configuration.provider` to the value `cfg4j` when starting the kernel application via the `startKernel.sh` and `startKernel.bat` files. See, for example, the `startKernel.bat` file ([1]) where you would adjust the value “gestalt” to “cfg4j”. This will configure the kernel application to use the old/previous configuration library. When you want to run the kernel application via Gralde, you have to set the corresponding system property in the kernel project's `build.gradle` file (see [2]).

[1]: https://github.com/openTCS/opentcs-integration-example/blob/b96b3bfcd80c07a5229eb7b4b65e6932ae191b0b/openTCS-Example-Kernel/src/dist/startKernel.bat#L29
[2]: https://github.com/openTCS/opentcs-integration-example/blob/b96b3bfcd80c07a5229eb7b4b65e6932ae191b0b/openTCS-Example-Kernel/build.gradle#L61
